# -*- coding: utf-8 -*-
"""wsgi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uOM6WTaK15lowGB_2zJKNIEdZBGmW3XZ
"""

from disease.main import app

if __name__ == "__main__":
    app.run()